site_name: GenAI Engineering Thailand
site_description: An active Generative AI community based in Thailand.
site_author: GenAI Engineering Thailand

# Repository
repo_name: genai-engineering-thailand.github.io
repo_url: https://github.com/genai-engineering-thailand/genai-engineering-thailand.github.io
edit_uri: "blob/main/docs/"

docs_dir: docs/
use_directory_urls: true

theme:
  name: material
  language: en
  logo: assets/logo-genai-engineer-thailand.png
  favicon: assets/logo-genai-engineer-thailand.png
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
    - navigation.top
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    # Palette toogle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      accent: purple
      primary: black
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      accent: purple
      primary: black

markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 4
      title: Page Sections
  - attr_list
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets # render markdown in markdown
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.pathconverter:
      base_path: "awesome-knowledge" # default: ''
      relative_path: "" # default ''
      absolute: false # default: false
      tags: "a script img link object embed"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - macros:
      on_undefined: strict
  - include_dir_to_nav:
      #file_pattern: '.*\.pdf$'
      recurse: true
      flat: false
      file_name_as_title: false
      include_empty_dir: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - mkdocs-jupyter:
          include: ["*.ipynb"]
          execute: false
          ignore_h1_titles: True

# Page tree
nav:
  - Home: "index.md"
  - Knowledge Sharing:
      - Content Index: "knowledge-sharing/content_index.md"
      - Self-hosted LLM On GCP:
          - "knowledge-sharing/0 - Self-hosted LLM on GCP"
      - PDF-to-Text - A nightmare that never ends:
          - "knowledge-sharing/1 - PDF-to-Text - A nightmare that never ends"
      - Introduction to Ollama:
          - "knowledge-sharing/2 - Introduction to Ollama"
      - Build AI App with Vercel SDK:
          - "knowledge-sharing/3 - Build AI App with Vercel SDK"
      - Monitoring and Observability in LLM Application:
          - "knowledge-sharing/4 - Monitoring and Observability in LLM Application"
      - Optimizing LLM with LoRA:
          - "knowledge-sharing/5 - Optimizing LLM with LoRA"
          - notebooks:
            - 1.Generate_json: knowledge-sharing/5 - Optimizing LLM with LoRA/material/fintune-llm-with-lora/01.Generate_json.ipynb
            - 2.Json_to_text: knowledge-sharing/5 - Optimizing LLM with LoRA/material/fintune-llm-with-lora/02.Json_to_text.ipynb
            - 3.Finetuning: knowledge-sharing/5 - Optimizing LLM with LoRA/material/fintune-llm-with-lora/03.Finetuning.ipynb
            - 4.Evaluate: knowledge-sharing/5 - Optimizing LLM with LoRA/material/fintune-llm-with-lora/04.Evaluate.ipynb
  - Content Curations: "awesome_curation.md"
